return {
  lua = true,
  python = true,
  javascript = true,
  typescript = true,
  typescriptreact = true,
  javascriptreact = true,
  tsx = true,
  jsx = true,
  svelte = true,
  html = true,
  css = true,
  json = true,
  bash = true,
  yaml = true,
}
